name: CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        container: [ "ubuntu:latest", "ubuntu:22.04", "debian:12", "debian:11", "archlinux:base" ]

    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.container }}
      options: --privileged

    steps:
      - name: install packages
        run: |
          uname -a
          case "${{ matrix.container }}" in
          ubuntu*|debian*)
            apt update
            apt upgrade -y
            apt install -y build-essential pkg-config bmake libbsd-dev libwebp-dev libssl-dev
            ;;
          archlinux*)
            pacman -Syyu --noconfirm base-devel bmake libbsd libwebp openssl
            ;;
          esac

      - uses: actions/checkout@v4
        with:
          #repository: isaki68k/sayaka
          fetch-depth: 200

      - name: configure and make
        run: |
          echo build with \"configure\"
          bmake distclean
          sh configure ${CONFIGURE_ARGS}
          bmake -DRELEASE

  build-netbsd:
    name: "build-netbsd (NetBSD/amd64 10.0 with pkgsrc)"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install packages and run configure and make (on the NetBSD VM)
        uses: vmactions/netbsd-vm@v1
        with:
          release: "10.0"
          copyback: false
          # Check https://github.com/NetBSD/pkgsrc/blob/trunk/net/sayaka/Makefile to check dependencies
          prepare: |
            uname -a
            pkg_add pkgconf
            pkg_add libwebp

          run: |
            echo build with \"configure\"
            make distclean
            sh configure
            make -DRELEASE

  build-openbsd:
    name: "build-openbsd (OpenBSD/amd64 7.6 with ports)"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install packages and run configure and make (on the OpenBSD VM)
        uses: vmactions/openbsd-vm@v1
        with:
          release: "7.6"
          copyback: false
          prepare: |
            uname -a
            pkg_add pkgconf
            pkg_add libwebp

          run: |
            echo build with \"configure\"
            make distclean
            sh configure
            make -DRELEASE

  build-freesd:
    name: "build-freebsd (FreeBSD/amd64 14.2 with ports)"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install packages and run configure and make (on the FreeBSD VM)
        uses: vmactions/freebsd-vm@v1
        with:
          release: "14.2"
          copyback: false
          prepare: |
            uname -a
            pkg install -y pkgconf
            pkg install -y webp

          run: |
            set -e
            echo build with \"configure\"
            make distclean
            sh configure
            make -DRELEASE
