name: CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: install packages
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y build-essential pkg-config bmake libbsd-dev libwslay-dev libwebp-dev libmbedtls-dev

      - uses: actions/checkout@v4
        with:
          #repository: isaki68k/sayaka
          fetch-depth: 200

      - name: configure and make
        run: |
          sh configure
          bmake -DRELEASE sayaka

  build-netbsd:
    name: "build-netbsd (NetBSD/amd64 9.3 with pkgsrc)"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install packages and run configure and make (on the NetBSD VM)
        uses: vmactions/netbsd-vm@v1
        with:
          usesh: true
          copyback: false
          # Check https://github.com/NetBSD/pkgsrc/blob/trunk/net/sayaka/Makefile to check dependencies
          prepare: |
            PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin:/usr/pkg/bin:/usr/pkg/sbin:/usr/games:/usr/local/bin:/usr/local/sbin
            export PATH
            pkg_add pkgconf
            pkg_add gcc10
            pkg_add libwebp mbedtls wslay

          run: |
            PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin:/usr/pkg/bin:/usr/pkg/sbin:/usr/games:/usr/local/bin:/usr/local/sbin
            export PATH=/usr/pkg/gcc10/bin:${PATH}
            CC=/usr/pkg/gcc10/bin/gcc CXX=/usr/pkg/gcc10/bin/g++ sh configure
            make -DRELEASE sayaka

  build-openbsd:
    name: "build-openbsd (OpenBSD/amd64 7.4 with pkgsrc)"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install packages and run configure and make (on the OpenBSD VM)
        uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          copyback: false
          prepare: |
            PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin
            export PATH
            pkg_add pkgconf
            pkg_add libwebp mbedtls wslay

          run: |
            sh configure
            make -DRELEASE sayaka
